language: cpp
sudo: false

matrix:
  allow_failures:
  - os: osx

  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
        packages: ['gcc-5', 'g++-5', 'cmake', 'cmake-data']
    env: CXX_COMPILER="g++-5" C_COMPILER="gcc-5"

  - os: linux
    compiler: clang
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7', 'george-edison55-precise-backports']
        packages: ['gcc-5', 'g++-5', 'clang-3.7', 'cmake', 'cmake-data']
    env: CXX_COMPILER="clang++-3.7" C_COMPILER="clang-3.7"

  - os: osx
    compiler: clang
    env: CXX_COMPILER='clang++' C_COMPILER='clang'

before_script:
- export CXX=${CXX_COMPILER}
- export CC=${C_COMPILER}

script: ./.travis.sh

notifications:
  email: false
